### ISSUE TITLE
Extension: Support autoreload attribute

### ISSUE THREAD

**Issue by robindeclercq** [silverfin/silverfin-cli#102]
**Describe the bug**
For boolean and radioinputs autoreload:true can now be added as attribute

**Additional context**
Documentation has not been written - in case of questions please reach out

**Comment by Toby-Masters-SF** [comment]
@robindeclercq added in draft snippet/documentation, but will reach out on slack to clarify meaning

**Comment by Woetfin** [comment]
Part of the extension instead of CLI and will be taken up with this issue: https://github.com/silverfin/silverfin-vscode/issues/5
