### ISSUE TITLE
Possibility to make liquid errors more descriptive (similar to platform)

### ISSUE THREAD

**Issue by BenjaminLangenakenSF** [silverfin/silverfin-cli#110]
Ran into a liquid error while running my liquid test:
`Liquid error: undefined method "to_d" for true:TrueClass `
![image](https://github.com/silverfin/silverfin-cli/assets/120387086/9f160a46-7ef1-40f9-95b8-905bd19e7818)

On the platform we get more info about the exact issue that occurs:
![image](https://github.com/silverfin/silverfin-cli/assets/120387086/7d14a182-e1ed-4532-b987-69acbbac6d6f)

Could we somehow also show these errors on the CLI?

Thanks!

**Comment by Woetfin** [comment]
This will probably be something to improve by engineering, as we just display the error we get back from the Silverfin API

**Comment by Woetfin** [comment]
I've created a ticket for this on the internal engineering board: EXTSFENG-285
