### ISSUE TITLE
Improve error messaging when we encounter a broken config.json

### ISSUE THREAD

**Issue by AgustinSilverfin** [silverfin/silverfin-cli#114]
**Describe the bug**
When the JSON file for the config is broken (there are issues with it's syntax, like trailing commas) it will raise an error that is not handled.
[Further details](https://silverfin.slack.com/archives/C0376K9NNTS/p1708959117735619)

**Expected behavior**
It would be good to catch that error, to be able to identify in which file it happen, and give information to the user in which json to look into

**Screenshots or Pull request**
![image](https://github.com/silverfin/silverfin-cli/assets/99397124/b5f25375-9abf-4154-a60a-2b8336d9aeaa)

**Desktop & CLI (please complete the following information):**
 - CLI version (run `silverfin --version`): [e.g. 1.0.0]

**Additional context**

**Comment by Woetfin** [comment]
In version 1.26.8, you should now get pointed towards which template / shared part has an issue if there's an error thrown in the config:
![image](https://github.com/silverfin/silverfin-cli/assets/99254741/1572822f-825c-48f2-8580-0c9c95af94a7)
