### ISSUE TITLE
Not permitted to update new template

### ISSUE THREAD

**Issue by RomySilverfin** [silverfin/silverfin-cli#121]
**Describe the bug**
After creating a new reconciliation through the CLI, when I try to update that reconciliation I get an error.

 Response Error (422): {"downloadable_as_docx":"found unpermitted parameter: downloadable_as_docx for non externally managed template"} 
 You don't have the rights to update the previous parameters

I authorized the firm again but the issue persists.

**To Reproduce**
1. Create new recon. with the CLI
2. Update the main.liquid with some code
3. Run the update command through the CLI or try using development mode

**Expected behavior**
Recon. is updated in the firm

**Screenshots or Pull request**

**Desktop & CLI (please complete the following information):**
 - OS: macOS Sonoma 14.4
 - CLI version 1.26.4

**Additional context**

**Comment by RomySilverfin** [comment]
Workaround: manually remove the downloadable_as_docx parameter from the config.json

**Comment by Woetfin** [comment]
This should already not happen as often anymore due to engineering update of making `externally_managed` already able to be set on template creation

**Comment by RomySilverfin** [comment]
It doesn't show the error message anymore, but it's still not possible to update templates created through the CLI without removing the downloadable as docx parameter.

**Comment by AgustinSilverfin** [comment]
> It doesn't show the error message anymore, but it's still not possible to update templates created through the CLI without removing the downloadable as docx parameter.

@RomySilverfin  Could you provide further details? Is it externally managed? Is it downloadable as docx?
