### ISSUE TITLE
Make messages mandatory when updating the partners version of templates

### ISSUE THREAD

**Issue by Toby-Masters-SF** [silverfin/silverfin-cli#123]
**Is your feature request related to a problem? Please describe.**
All partners template updates should have a meaningful message. However, as the message is not currently mandatory its easy to forgot when updating and have the commit history populated by 'Updated by Silverfin CLI'

**Describe the solution you'd like**
When the Partner flag is used for update-reconciliation, update-shared-part etc, the message flag should be **mandatory**

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Woetfin** [comment]
Would indeed be valid to implement
