### ISSUE TITLE
Make error messages refer to the correct handle when catching errors

### ISSUE THREAD

**Issue by BenjaminLangenakenSF** [silverfin/silverfin-cli#127]
Would it be possible to have error messages referring to the correct handle?

Example:
Below error message referred to the wrong handle, which was a bit confusing.
![image](https://github.com/silverfin/silverfin-cli/assets/120387086/0a2bfc77-c1c4-430b-a5ef-53b68df50e60)

The issue occurred in a different config file though:
![image](https://github.com/silverfin/silverfin-cli/assets/120387086/687dcdbe-9818-4751-9e1b-17923406d98e)

**Comment by Woetfin** [comment]
I'm already adding some additional user feedback for errors inside the PR #120 ; so I'll also add an improved error message for this one in the same PR

**Comment by BenjaminLangenakenSF** [comment]
Perfect thanks!

**Comment by Woetfin** [comment]
@BenjaminLangenakenSF 

In version 1.26.8, you should now get pointed towards which template / shared part has an issue if there's an error thrown in the config:
![image](https://github.com/silverfin/silverfin-cli/assets/99254741/1572822f-825c-48f2-8580-0c9c95af94a7)
