### ISSUE TITLE
Coding new shared part with variables, and not yet added, will not fault in LT

### ISSUE THREAD

**Issue by Snakefin** [silverfin/silverfin-cli#137]
**Describe the bug**

If you code a shared part with variables, while the shared part itself has not yet been added, then our LT will not give an error and say that the shared part hasn't been added yet : 

`{% include "shared/lux_perc" to_check_perc:custom.some.perc %}`

![Screenshot 2024-06-24 at 10 23 02](https://github.com/silverfin/silverfin-cli/assets/104010308/13069e8b-51e0-40d8-975d-f41f7934a97f)

--> however, if you remove `to_check_perc:custom.some.perc`, our LT all of a sudden does recognise that the shared part is not added yet, and gives a warning

**Screenshots or Pull request**
If applicable, add screenshots or the link to a pull request to help explain your problem.

**Desktop & CLI (please complete the following information):**

**1.26.12**

**Additional context**

See https://silverfin.slack.com/archives/C01SYB7FS05/p1719217553731989?thread_ts=1718961279.980619&cid=C01SYB7FS05

**Comment by AgustinSilverfin** [comment]
@Snakefin Should be solved in VS Code extension latest version (1.18.0)
