### ISSUE TITLE
Templates: add message to update-reconciliation command

### ISSUE THREAD

**Issue by robbedewildeSF** [silverfin/silverfin-cli#51]
**Is your feature request related to a problem? Please describe.**
When we use update-reconciliation, we are currently not able to add a description to the update. 
It always says **Update published using the API**
<img width="700" alt="Screenshot 2023-08-10 at 09 23 21" src="https://github.com/silverfin/sf_toolkit/assets/103578177/91ba1cbb-e018-4134-ba4d-4923223f9561">

**Describe the solution you'd like**
It would be usefull for testing in the platform that we can add a description to the updates we are pushing to the platform
`silverfin update-reconciliation -h my_template -f 12345 -m "beta release order 67"`

**Comment by AgustinSilverfin** [comment]
@robbedewildeSF I will address this one together with the new release we are working on #50
