### ISSUE TITLE
CLI: add rate limiting for update-shared-part command

### ISSUE THREAD

**Issue by Woetfin** [silverfin/silverfin-cli#70]
**Is your feature request related to a problem? Please describe.**
When updating the same shared part or multiple shared parts linked to the same reconciliation in quick succession (e.g. 10 updates in a single second), which could be easily possible using Actions, this gives errors like `ActiveRecord::LockWaitTimeout Sidekiq/SharedPartUpdateJob Level: Error PG::LockNotAvailable: ERROR: canceling statement due to lock timeout ` on the background in Silverfin. 

This is mainly caused because when updating a shared part, it also creates jobs to update all underlying reconciliations / account templates linked to that shared part, so we'd need to find a way so the system has enough time to create these update jobs correctly when updating multiple shared parts for the same template. 

**Describe the solution you'd like**
We should add a rate limit for shared part updates, so the system has a reasonable time to update all underlying reconciliations / account templates before another request for updating a shared part is sent. 

**Describe alternatives you've considered**
No alternatives

**Additional context**
Notified about the issue inside internal Slack channel in Silverfin

**Comment by AgustinSilverfin** [comment]
Not sure if it will fully solve it, but an update was implemented for this ([here](https://github.com/silverfin/silverfin-cli/issues/97#issuecomment-1865930878)). We can re-open these tickets if issues reappears
