### ISSUE TITLE
CLI: development-mode gets into some kind of loop

### ISSUE THREAD

**Issue by Snakefin** [silverfin/silverfin-cli#74]
**Describe the bug**

When activating the development mode with the command `silverfin development-mode --update-templates --yes`, a weird thing happens where all of a sudden several RT's are updated (which didn't have to do anything with the change I did in another RT). 

Screenshot of the updates being in a loop: 
![Screenshot 2023-10-04 at 13 53 28](https://github.com/silverfin/silverfin-cli/assets/104010308/a49889a1-4868-4d05-9425-49a0054b509e)

Screenshot of the changed files of unrelated RT's: 
![Screenshot 2023-10-04 at 13 53 46](https://github.com/silverfin/silverfin-cli/assets/104010308/e52984e6-e687-4741-acb9-2cc59616f5f0)

Screenshot of the done change: 
![Screenshot 2023-10-04 at 13 53 51](https://github.com/silverfin/silverfin-cli/assets/104010308/7cf6c609-f3ff-4411-b041-913fe6c5cadb)

**To Reproduce**
1. Activate development mode
2. Add change to local file 
3. Save the file 

**Expected behavior**

What I would expect, is in the terminal an update is done in the related RT of the change (and only that). 

**Screenshots or Pull request**

See above

**Desktop & CLI (please complete the following information):**
 - OS: MacOS Ventura 13.6
 - CLI version (run `silverfin --version`): **1.20.2**

**Additional context**

Was discussed with Woet as well; see [here](https://silverfin.slack.com/archives/C0376K9NNTS/p1695906264911449)

**Comment by Woetfin** [comment]
version 1.26.5 in #116 will hopefully resolved this for good
